### ISSUE TITLE
Early Access 

### ISSUE THREAD

**Issue by zbanga** [Zymrael/wattnet-fx-trading#1]
Hello, 

I was wondering if I could get early access to the script for cleaning, preprocessing the data and the model.

**Comment by Zymrael** [comment]
Thank you for your interest. I will send the model soon (next 2/3 days max). The data scripts will come later, ETA 10 days approx.

**Comment by zbanga** [comment]
Thank You! I look forward to your model!

**Comment by Zymrael** [comment]
Code for main model and supporting modules has been uploaded, enjoy.
