### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by firmai** [Zymrael/wattnet-fx-trading#2]
Hi man, unrelated to this project, I saw you starred my PDE discovery repository. You have done some very interesting work. If you can have a look at what I want to do, let me know if it is achievable. If you have expertise in this area, I would be happy to collaborate, I can get us optionmetrics data through NYU. 

https://github.com/firmai/financial-pde-discovery

**Comment by Zymrael** [comment]
Thanks for reaching out. PDE discovery is not my main focus area, but I would start from here: https://arxiv.org/abs/1710.09668 and all its follow-up works.
