### ISSUE TITLE
Release the data?

### ISSUE THREAD

**Issue by crameth** [Zymrael/wattnet-fx-trading#3]
It's been about 3 months, are you planning on releasing the scripts to download the data?

**Comment by Zymrael** [comment]
Hello, thank you for the interest. Some of the scripts are already available, the only missing component is a (much smaller) script to download DTCC NDF data. Preprocessing for the raw DTCC dataset is already available under `scripts`. 

We will release the remaining components after the review phase of our paper is completed.
