### ISSUE TITLE
How to set the hyperparameter ‘in_dim ’ in WATTNet?

### ISSUE THREAD

**Issue by qiao1406** [Zymrael/wattnet-fx-trading#4]
Should this hyperparameter be set **equal** to the number of time series？

when `x_in` in shape `(N, C, H, W)`, should `in_dim` set equal to `W`

**Comment by qiao1406** [comment]
p.s. What are `preMLP` and `postMLP` used for?

**Comment by Zymrael** [comment]
Hi @qiao1406, thanks for asking. 

(1) You're correct, `in_dim` should be `W`
(2) A simple means to change the dimensionality. For example `postMLP` is useful when the pyramid structure of WATTNet does not leave you with the desired output dimensions. You can use other components, such as an `RNN/LSTM` there.

**Comment by qiao1406** [comment]
thank you!
