### ISSUE TITLE
implementation of residual connection

### ISSUE THREAD

**Issue by aliamiri1380** [Zymrael/wattnet-fx-trading#5]
Hi,
I think the implementation of residual connection of gated block is incorrect
because in the WaveNet architecture the multiplication is fed into a 1*1 Conv then the output of this Conv added by the input
https://github.com/Zymrael/wattnet-fx-trading/blob/master/torchNDF/models/modules.py#L58

**Comment by Zymrael** [comment]
Hi @aliamiri1380, you can find both versions floating around. In this specific instance, I found the current version to perform slightly better, even though your mileage may vary.

**Comment by aliamiri1380** [comment]
thank you for the answer
